version: '3'
services:
  movie:
    image: sudhir12/movieservice:lastest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  train:
    image: sudhir12/trainservice:lastest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  dth:
    image: sudhir12/dthservice:lastest
    ports:
      - "83:80"
    deploy:
      replicas: 3

  recharge:
    image: sudhir12/moviesservice:lastest
    ports:
      - "84:80"
    deploy:
      replicas: 3
