version: '3'
services:
  aws:
    image: sudhir12/aws
    ports:
      - "95:80"
    deploy:
      replicas: 3

  devops:
    image: sudhir12/devops
    ports:
      - "96:80"
    deploy:
      replicas: 3

  azure:
    image: sudhir12/azure
    ports:
      - "97:80"
    deploy:
      replicas: 3
  ds:
    image: sudhir12/ds
    ports:
      - "98:80"
    deploy:
      replicas: 3
